import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.ArrayList;

public class buku extends javax.swing.JFrame {

    /**
     * Creates new form buku
     */
   public buku() {
        initComponents();
        setLocationRelativeTo(null);
//        findUsers();
        loadData();
    }
   
//   public ArrayList<search> ListSearch(String ValToSearch)
//    {
//        ArrayList<search> usersList = new ArrayList<search>();
//        
//        Statement st = null;
//        ResultSet rs;
//        
//        try{
//            java.sql.Connection conn = (Connection) koneksi2.koneksiDB();
//            java.sql.Statement stm = conn.createStatement();
//            String searchQuery = "SELECT * FROM `buku` WHERE 1 `id_buku`, `judul`, `penerbit`, `pengarang`, `jenis`, `tahun` LIKE '%"+ValToSearch+"%'";
//            rs = st.executeQuery(searchQuery);
//            
//            search user;
//            
//            while(rs.next())
//            {
//                user = new search(
//                                 rs.getInt("id_buku"),
//                                 rs.getString("judul"),
//                                 rs.getString("pengarang"),
//                                 rs.getString("penerbit"),
//                                 rs.getString("jenis"),
//                                 rs.getString("tahun")
//                                );
//                usersList.add(user);
//            }
//            
//        }catch(Exception e){
//            System.out.println(e.getMessage());
//        }
//        
//        return usersList;
//    }
//   
//   public void findUsers()
//    {
//        ArrayList<search> users = ListSearch(search.getText());
//        DefaultTableModel model = new DefaultTableModel();
//        model.setColumnIdentifiers(new Object[]{"ID Buku","Judul","Penerbit","Pengarang","Jenis","Tahun"});
//        Object[] row = new Object[6];
//        
//        for(int i = 0; i < users.size(); i++)
//        {
//            row[0] = users.get(i).getid_buku();
//            row[1] = users.get(i).getjudul();
//            row[2] = users.get(i).getpenerbit();
//            row[3] = users.get(i).getpengarang();
//            row[4] = users.get(i).getjenis();
//            row[5] = users.get(i).gettahun();
//            model.addRow(row);
//        }
//       txt_table.setModel(model);
//       
//    }
      
    private void loadData(){  
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Buku");
    model.addColumn("Judul");
    model.addColumn("Penerbit");
    model.addColumn("Pengarang");
    model.addColumn("Jenis");
    model.addColumn("Tahun");
    
   
    try{
        String sql = "select * from buku";
        java.sql.Connection conn = (Connection) koneksi2.koneksiDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        while(res.next()){
            model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
        }
        txt_table.setModel(model);
        
    }catch(Exception e){
        System.out.println(e.getMessage());
    }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_idbuku = new javax.swing.JTextField();
        txt_judul = new javax.swing.JTextField();
        txt_penerbit = new javax.swing.JTextField();
        txt_pengarang = new javax.swing.JTextField();
        txt_jenis = new javax.swing.JTextField();
        txt_tahun = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_table = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Data Buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Data Buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Buku");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel3.setText("Judul");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setText("Penerbit");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel5.setText("Pengarang");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setText("Jenis");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel7.setText("Tahun");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        jPanel2.add(txt_idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 194, 30));
        jPanel2.add(txt_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 194, 30));
        jPanel2.add(txt_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 194, 30));
        jPanel2.add(txt_pengarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 194, 30));
        jPanel2.add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 194, 30));
        jPanel2.add(txt_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 194, 30));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 70, 40));

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 70, 40));

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 50, 40));

        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, 332, 380));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Buku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        txt_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txt_table);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 540, 280));

        jLabel8.setText("Cari Buku");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel3.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 120, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 66, 570, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String sql = "INSERT INTO buku(id_buku,judul,penerbit,pengarang,jenis,tahun)VALUES('"+txt_idbuku.getText()+"','"+txt_judul.getText()+"','"+txt_penerbit.getText()+"'"
                    + ",'"+txt_pengarang.getText()+"','"+txt_jenis.getText()+"','"+txt_tahun.getText()+"')";
              java.sql.Connection conn = (Connection) koneksi2.koneksiDB();
              java.sql.PreparedStatement pst = conn.prepareStatement(sql);
              pst.execute();
              JOptionPane.showMessageDialog(null, "Data anggota berhasil di simpan");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal di tambahkan");
        }
        loadData();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
           String sql = "update buku set id_buku = '"+txt_idbuku.getText()+"', nama = '"+txt_judul.getText()+"', penerbit = '"+txt_penerbit.getText()+"',pengarang = '"+txt_pengarang.getText()+"',jenis = '"+txt_jenis.getText()+"',tahun = '"+txt_tahun.getText()+"' where id_buku = '"+txt_idbuku.getText()+"' ";
           java.sql.Connection conn = (Connection) koneksi2.koneksiDB();
           java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        loadData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
              String sql = "DELETE FROM buku WHERE id_buku="+txt_idbuku.getText();
              java.sql.Connection conn = (Connection) koneksi2.koneksiDB();
              java.sql.PreparedStatement pst = conn.prepareStatement(sql);
              pst.execute();
              JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        loadData();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tableMouseClicked
       int baris = txt_table.rowAtPoint(evt.getPoint());
       String id_buku = txt_table.getValueAt(baris, 0).toString();
       txt_idbuku.setText(id_buku);
       String judul = txt_table.getValueAt(baris, 1).toString();
       txt_judul.setText(judul);
       String penerbit = txt_table.getValueAt(baris, 2).toString();
       txt_penerbit.setText(penerbit);
       String pengarang = txt_table.getValueAt(baris, 3).toString();
       txt_pengarang.setText(pengarang);
       String jenis = txt_table.getValueAt(baris, 4).toString();
       txt_jenis.setText(jenis);
       String tahun = txt_table.getValueAt(baris, 4).toString();
       txt_tahun.setText(tahun);
    }//GEN-LAST:event_txt_tableMouseClicked

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
//        findUsers();
    }//GEN-LAST:event_searchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new utama().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    private javax.swing.JTextField txt_idbuku;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_judul;
    private javax.swing.JTextField txt_penerbit;
    private javax.swing.JTextField txt_pengarang;
    private javax.swing.JTable txt_table;
    private javax.swing.JTextField txt_tahun;
    // End of variables declaration//GEN-END:variables
}
